apiVersion: apps/v1
kind: Deployment
metadata:
  name: american-predictor-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catarinaedp-american-predictor
  template:
    metadata:
      labels:
        app: catarinaedp-american-predictor
    spec:
      containers:
      - name: american-predictor
        image: catarinaedp/american-predictor:v2.0.11
        ports:
        - containerPort: 5006