apiVersion: v1
kind: Service
metadata:
  name: american-predictor-service
spec:
  selector:
    app: catarinaedp-american-predictor
  ports:
    - protocol: TCP
      port: 5006
      targetPort: 5006